#include "coverage/instrumenter.h"
#include <QFile>
#include <QTextStream>
#include <QFileInfo>
#include <QDir>
#include <QRegularExpression>

namespace Coverage {

QJsonObject InstrumentationMetadata::toJson() const {
    QJsonObject obj;
    obj[QStringLiteral("sourceFilePath")] = sourceFilePath;
    obj[QStringLiteral("instrumentedFilePath")] = instrumentedFilePath;
    obj[QStringLiteral("totalProbeLines")] = totalProbeLines;
    obj[QStringLiteral("totalProbeBranches")] = totalProbeBranches;
    obj[QStringLiteral("totalProbeFunctions")] = totalProbeFunctions;

    QJsonObject lineObj;
    for (auto it = lineToProbeId.constBegin(); it != lineToProbeId.constEnd(); ++it) {
        lineObj[QString::number(it.key())] = it.value();
    }
    obj[QStringLiteral("lineToProbeId")] = lineObj;

    QJsonObject branchObj;
    for (auto it = branchProbes.constBegin(); it != branchProbes.constEnd(); ++it) {
        branchObj[QString::number(it.key())] = it.value().toJson();
    }
    obj[QStringLiteral("branchProbes")] = branchObj;

    QJsonObject funcObj;
    for (auto it = functionProbes.constBegin(); it != functionProbes.constEnd(); ++it) {
        funcObj[QString::number(it.key())] = it.value();
    }
    obj[QStringLiteral("functionProbes")] = funcObj;

    return obj;
}

InstrumentationMetadata InstrumentationMetadata::fromJson(const QJsonObject& json) {
    InstrumentationMetadata m;
    m.sourceFilePath = json[QStringLiteral("sourceFilePath")].toString();
    m.instrumentedFilePath = json[QStringLiteral("instrumentedFilePath")].toString();
    m.totalProbeLines = json[QStringLiteral("totalProbeLines")].toInt();
    m.totalProbeBranches = json[QStringLiteral("totalProbeBranches")].toInt();
    m.totalProbeFunctions = json[QStringLiteral("totalProbeFunctions")].toInt();

    QJsonObject lineObj = json[QStringLiteral("lineToProbeId")].toObject();
    for (auto it = lineObj.constBegin(); it != lineObj.constEnd(); ++it) {
        m.lineToProbeId[it.key().toInt()] = it.value().toInt();
    }

    QJsonObject branchObj = json[QStringLiteral("branchProbes")].toObject();
    for (auto it = branchObj.constBegin(); it != branchObj.constEnd(); ++it) {
        m.branchProbes[it.key().toInt()] = BranchPoint::fromJson(it.value().toObject());
    }

    QJsonObject funcObj = json[QStringLiteral("functionProbes")].toObject();
    for (auto it = funcObj.constBegin(); it != funcObj.constEnd(); ++it) {
        m.functionProbes[it.key().toInt()] = it.value().toString();
    }

    return m;
}

QString Instrumenter::generateEmbeddedRuntimeHeader() {
    return QStringLiteral(
R"(#ifndef COVERAGE_RUNTIME_H
#define COVERAGE_RUNTIME_H

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Embedded Coverage Runtime - Ultra lightweight probe tracking */
static inline void _cov_hit_line(int file_id, int line) {
    printf("[COV] L:%d:%d\n", file_id, line);
    fflush(stdout);
}

static inline void _cov_hit_func(int func_id) {
    printf("[COV] F:%d\n", func_id);
    fflush(stdout);
}

static inline int _cov_hit_branch(int branch_id, int cond) {
    if (cond) {
        printf("[COV] B:%d:T\n", branch_id);
    } else {
        printf("[COV] B:%d:F\n", branch_id);
    }
    fflush(stdout);
    return cond ? 1 : 0;
}

#ifdef __cplusplus
}
#endif

#endif /* COVERAGE_RUNTIME_H */
)");
}

Instrumenter::InstrumentResult Instrumenter::instrumentSource(const QString& sourceCode, const QString& sourceFileName) {
    InstrumentResult result;
    result.metadata.sourceFilePath = sourceFileName;

    QStringList lines = sourceCode.split(QStringLiteral("\n"));
    QString outputCode;
    outputCode += QStringLiteral("/* --- Auto-Generated by Embedded C Coverage Instrumenter --- */\n");
    outputCode += QStringLiteral("#include \"coverage_runtime.h\"\n\n");

    int probeId = 1;
    int branchId = 1;
    int funcId = 1;

    static const QRegularExpression ifRegex(QStringLiteral(R"((\bif\s*\()([^;]+?)(\)\s*\{?))"));
    static const QRegularExpression funcSigRegex(
        QStringLiteral(R"(^(?:static\s+|extern\s+|inline\s+)*([a-zA-Z0-9_]+(?:\s*\*+)?)\s+([a-zA-Z0-9_]+)\s*\(([^;)]*)\)\s*(\{?))")
    );

    auto isVariableDeclaration = [](const QString& str) -> bool {
        if (str.isEmpty() || !str.endsWith(QLatin1Char(';'))) return false;
        if (str.startsWith(QStringLiteral("return")) ||
            str.startsWith(QStringLiteral("break")) ||
            str.startsWith(QStringLiteral("continue")) ||
            str.startsWith(QStringLiteral("goto "))) {
            return false;
        }
        if (str.startsWith(QStringLiteral("typedef")) ||
            str.startsWith(QStringLiteral("struct")) ||
            str.startsWith(QStringLiteral("enum")) ||
            str.startsWith(QStringLiteral("extern"))) {
            return true;
        }
        // Exclude pointer/assignment like `controller->speed = 0.0f;` or `arr[i] = 1;`
        if (str.contains(QStringLiteral("->")) || str.startsWith(QLatin1Char('*'))) {
            if (!str.startsWith(QStringLiteral("void*")) && !str.startsWith(QStringLiteral("char*")) && !str.startsWith(QStringLiteral("int*"))) {
                return false;
            }
        }
        static const QRegularExpression varDecl(
            QStringLiteral(R"(^(?:static\s+|const\s+|volatile\s+|register\s+)*(?:(?:unsigned|signed|short|long)\s+)*(?:void|int|char|short|long|float|double|bool|_Bool|size_t|u?int(?:8|16|32|64)_t|float32_t|float64_t|[a-zA-Z0-9_]+_t|[A-Z][a-zA-Z0-9_]*)(?:\s*\*+|\s+)\s*([a-zA-Z0-9_]+)(?:\[[^\]]*\])?(?:\s*=\s*[^;]+)?\s*;)")
        );
        return varDecl.match(str).hasMatch();
    };

    bool inMultiComment = false;
    int braceDepth = 0;
    int pendingFuncId = -1;

    for (int i = 0; i < lines.size(); ++i) {
        int originalLineNum = i + 1;
        QString line = lines[i];

        // 1. 处理跨行多行注释 /* ... */
        QString codeWithoutComments = line;
        if (inMultiComment) {
            int endCommentIdx = codeWithoutComments.indexOf(QStringLiteral("*/"));
            if (endCommentIdx != -1) {
                codeWithoutComments = codeWithoutComments.mid(endCommentIdx + 2);
                inMultiComment = false;
            } else {
                outputCode += line + QStringLiteral("\n");
                continue;
            }
        }

        // 2. 剥离当前行内所有的 /* ... */ 块注释
        while (true) {
            int startIdx = codeWithoutComments.indexOf(QStringLiteral("/*"));
            if (startIdx == -1) break;
            int endIdx = codeWithoutComments.indexOf(QStringLiteral("*/"), startIdx + 2);
            if (endIdx != -1) {
                codeWithoutComments.remove(startIdx, (endIdx + 2) - startIdx);
            } else {
                codeWithoutComments = codeWithoutComments.left(startIdx);
                inMultiComment = true;
                break;
            }
        }

        // 3. 剥离单行 // ... 注释
        int slashSlashIdx = codeWithoutComments.indexOf(QStringLiteral("//"));
        if (slashSlashIdx != -1) {
            codeWithoutComments = codeWithoutComments.left(slashSlashIdx);
        }

        QString cleanTrimmed = codeWithoutComments.trimmed();

        // 纯注释行、预编译指令宏行或空行：不参与分支判定与探针插桩
        if (cleanTrimmed.isEmpty() || cleanTrimmed.startsWith(QLatin1Char('#'))) {
            outputCode += line + QStringLiteral("\n");
            continue;
        }

        // 统计剔除注释后的代码有效花括号深度
        int openBraces = codeWithoutComments.count(QLatin1Char('{'));
        int closeBraces = codeWithoutComments.count(QLatin1Char('}'));

        // Check if previous line had a function signature waiting for opening brace '{'
        if (pendingFuncId != -1) {
            outputCode += line + QStringLiteral("\n");
            if (codeWithoutComments.contains(QLatin1Char('{'))) {
                outputCode += QString("    _cov_hit_func(%1);\n").arg(pendingFuncId);
                pendingFuncId = -1;
            }
            braceDepth += (openBraces - closeBraces);
            braceDepth = qMax(0, braceDepth);
            continue;
        }

        // 1. Check function entry at file scope (braceDepth == 0)
        if (braceDepth == 0) {
            auto funcMatch = funcSigRegex.match(cleanTrimmed);
            if (funcMatch.hasMatch() &&
                funcMatch.captured(2) != QStringLiteral("if") &&
                funcMatch.captured(2) != QStringLiteral("while") &&
                funcMatch.captured(2) != QStringLiteral("for") &&
                funcMatch.captured(2) != QStringLiteral("switch"))
            {
                QString funcName = funcMatch.captured(2);
                result.metadata.functionProbes[funcId] = funcName;
                result.metadata.totalProbeFunctions++;

                if (cleanTrimmed.endsWith(QLatin1Char('{')) || codeWithoutComments.contains(QLatin1Char('{'))) {
                    outputCode += line + QString("\n    _cov_hit_func(%1);\n").arg(funcId);
                    braceDepth++;
                } else {
                    outputCode += line + QStringLiteral("\n");
                    pendingFuncId = funcId;
                }
                funcId++;
                continue;
            }
        }

        // 2. Check branch 'if (cond)' within a function (only match against cleanTrimmed!)
        auto ifMatch = ifRegex.match(cleanTrimmed);
        if (braceDepth > 0 && ifMatch.hasMatch()) {
            QString originalCondition = ifMatch.captured(2);
            BranchPoint bp;
            bp.branchId = branchId;
            bp.line = originalLineNum;
            bp.condition = originalCondition.trimmed();
            bp.trueHitCount = 0;
            bp.falseHitCount = 0;

            result.metadata.branchProbes[branchId] = bp;
            result.metadata.totalProbeBranches++;

            // Transform condition to wrap in _cov_hit_branch
            QString transformed = line;
            QString trailing = ifMatch.captured(3);
            if (trailing.startsWith(QLatin1Char(')'))) {
                trailing = trailing.mid(1);
            }
            QString replacement = QString("if (_cov_hit_branch(%1, (%2)))%3")
                                      .arg(branchId).arg(originalCondition).arg(trailing);
            transformed.replace(ifMatch.captured(0), replacement);

            outputCode += QString("    _cov_hit_line(1, %1);\n").arg(originalLineNum);
            outputCode += transformed + QStringLiteral("\n");

            result.metadata.lineToProbeId[originalLineNum] = probeId++;
            result.metadata.totalProbeLines++;
            branchId++;

            braceDepth += (openBraces - closeBraces);
            braceDepth = qMax(0, braceDepth);
            continue;
        }

        // 3. Regular statement line inside a function (braceDepth > 0)
        // Skip pure variable declarations, type definitions, and file-level definitions
        if (braceDepth > 0 && cleanTrimmed.endsWith(QLatin1Char(';'))) {
            if (!isVariableDeclaration(cleanTrimmed)) {
                outputCode += QString("    _cov_hit_line(1, %1);\n").arg(originalLineNum);
                outputCode += line + QStringLiteral("\n");
                result.metadata.lineToProbeId[originalLineNum] = probeId++;
                result.metadata.totalProbeLines++;

                braceDepth += (openBraces - closeBraces);
                braceDepth = qMax(0, braceDepth);
                continue;
            }
        }

        outputCode += line + QStringLiteral("\n");
        braceDepth += (openBraces - closeBraces);
        braceDepth = qMax(0, braceDepth);
    }

    result.success = true;
    result.instrumentedCode = outputCode;
    return result;
}

Instrumenter::InstrumentResult Instrumenter::instrumentFile(const QString& inputFilePath, const QString& outputFilePath) {
    QFile inFile(inputFilePath);
    if (!inFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        InstrumentResult r;
        r.errorMessage = QStringLiteral("Cannot open input file: ") + inFile.errorString();
        return r;
    }

    QString source = inFile.readAll();
    inFile.close();

    QString targetOut = outputFilePath;
    if (targetOut.isEmpty()) {
        QFileInfo fi(inputFilePath);
        targetOut = fi.absolutePath() + QDir::separator() + fi.baseName() + QStringLiteral(".inst.c");
    }

    InstrumentResult res = instrumentSource(source, inputFilePath);
    if (!res.success) return res;

    res.metadata.instrumentedFilePath = targetOut;

    // Write instrumented file
    QFile outFile(targetOut);
    if (outFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&outFile);
        out << res.instrumentedCode;
        outFile.close();
    }

    // Write runtime header in same folder
    QFileInfo outFi(targetOut);
    QString headerPath = outFi.absolutePath() + QDir::separator() + QStringLiteral("coverage_runtime.h");
    QFile hFile(headerPath);
    if (!hFile.exists() && hFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream hOut(&hFile);
        hOut << generateEmbeddedRuntimeHeader();
        hFile.close();
    }

    return res;
}

} // namespace Coverage
