/* --- Auto-Generated by Embedded C Coverage Instrumenter --- */
#include "coverage_runtime.h"

/**
 * @file main_embedded.c
 * @brief 车载永磁同步电机(PMSM)控制器主入口与多速率周期调度器
 * @note 遵循 MISRA-C:2012 架构规范与 ISO 26262 ASIL-B 功能安全周期执行模型
 */

#include "motor_types.h"
#include "bsp_pwm.h"
#include "safety_monitor.h"
#include "can_comm.h"
#include <stdio.h>
#include <stdbool.h>

/* 全局系统遥测与状态结构 */
static MotorTelemetry_t g_telemetry = {
    .state = MOTOR_STATE_UNINITIALIZED,
    .mode = CTRL_MODE_SPEED,
    .speed_rpm = 0.0f,
    .torque_est = 0.0f,
    .vbus_volts = 48.0f,
    .ibus_amps = 0.0f,
    .temperature_c = 35.0f,
    .fault_flags = FAULT_NONE
    _cov_hit_line(1, 24);
};

    _cov_hit_line(1, 26);
static uint32_t g_system_tick_ms = 0;
    _cov_hit_line(1, 27);
static bool g_system_running = true;

/**
 * @brief 10kHz 高频矢量控制电流环 (模拟硬件定时器更新中断 ISR)
 */
void ISR_10kHz_CurrentLoop(void)
{
    // 1. 读取三相电流与母线电压
    _cov_hit_line(1, 35);
    PhaseCurrents_t currents;
    _cov_hit_line(1, 36);
    bsp_adc_read_phase_currents(&currents);
    _cov_hit_line(1, 37);
    g_telemetry.ibus_amps = currents.current_u;

    // 2. 只有在闭环或降额状态下才更新 PWM 矢量占空比
    _cov_hit_line(1, 40);
    if (_cov_hit_branch(1, (g_telemetry.state == MOTOR_STATE_CLOSED_LOOP || g_telemetry.state == MOTOR_STATE_DERATING))) {
        // 简化的空间矢量调制占空比计算
    _cov_hit_line(1, 42);
        float duty_u = 0.5f + 0.3f;
    _cov_hit_line(1, 43);
        float duty_v = 0.5f - 0.15f;
    _cov_hit_line(1, 44);
        float duty_w = 0.5f - 0.15f;
    _cov_hit_line(1, 45);
        BSP_PWM_SetDutyCycles(duty_u, duty_v, duty_w);
    } else {
        // 非运行状态保持安全关断
    _cov_hit_line(1, 48);
        bsp_pwm_disable_outputs();
    }
}

/**
 * @brief 100Hz 中频速度与状态机主控任务 (10ms 周期执行)
 */
void Task_100Hz_StateMachine(void)
{
    // 1. 喂安全看门狗
    _cov_hit_line(1, 58);
    safety_watchdog_kick();

    // 2. 模拟母线电压与温度动态波动
    _cov_hit_line(1, 61);
    g_telemetry.vbus_volts = 48.0f + 0.5f;
    _cov_hit_line(1, 62);
    g_telemetry.temperature_c = 42.0f;

    // 3. 执行功能安全全维度健康检查 (ASIL-B 门限判定)
    _cov_hit_line(1, 65);
    uint32_t active_faults = safety_monitor_evaluate(&g_telemetry);
    _cov_hit_line(1, 66);
    bool is_safe = (active_faults == FAULT_NONE);

    // 4. 周期检查 CAN 总线通信超时
    _cov_hit_line(1, 69);
    if (_cov_hit_branch(2, (!CAN_Comm_CheckTimeout(10)))) {
    _cov_hit_line(1, 70);
        safety_monitor_report_fault(FAULT_CAN_BUS_OFF);
    _cov_hit_line(1, 71);
        is_safe = false;
    }

    // 5. 获取最新故障掩码
    _cov_hit_line(1, 75);
    g_telemetry.fault_flags = safety_monitor_get_faults();

    // 6. 核心运行状态机转移逻辑
    switch (g_telemetry.state) {
        case MOTOR_STATE_UNINITIALIZED:
            // 初始未完成状态，等待初始化
    _cov_hit_line(1, 81);
            break;

        case MOTOR_STATE_STANDBY:
    _cov_hit_line(1, 84);
            if (_cov_hit_branch(3, (!is_safe))) {
    _cov_hit_line(1, 85);
                g_telemetry.state = MOTOR_STATE_FAULT;
            } else {
                // 模拟收到使能指令，转入电容预充
    _cov_hit_line(1, 88);
                g_telemetry.state = MOTOR_STATE_PRECHARGE;
            }
    _cov_hit_line(1, 90);
            break;

        case MOTOR_STATE_PRECHARGE:
            // 预充电完成检查，母线电压建立平稳后转入自定位
    _cov_hit_line(1, 94);
            if (_cov_hit_branch(4, (g_telemetry.vbus_volts > 36.0f))) {
    _cov_hit_line(1, 95);
                g_telemetry.state = MOTOR_STATE_ALIGNMENT;
            }
    _cov_hit_line(1, 97);
            break;

        case MOTOR_STATE_ALIGNMENT:
            // 完成转子初角磁极对齐，开启动力逆变器
    _cov_hit_line(1, 101);
            bsp_pwm_enable_outputs();
    _cov_hit_line(1, 102);
            g_telemetry.state = MOTOR_STATE_CLOSED_LOOP;
    _cov_hit_line(1, 103);
            break;

        case MOTOR_STATE_CLOSED_LOOP:
    _cov_hit_line(1, 106);
            if (_cov_hit_branch(5, (!is_safe))) {
    _cov_hit_line(1, 107);
                g_telemetry.state = MOTOR_STATE_FAULT;
    _cov_hit_line(1, 108);
                bsp_pwm_disable_outputs();
    _cov_hit_line(1, 109);
            } else if (_cov_hit_branch(6, (g_telemetry.temperature_c > 85.0f))) {
                // 达到降额温控线，进入保护降额模式
    _cov_hit_line(1, 111);
                g_telemetry.state = MOTOR_STATE_DERATING;
            } else {
                // 闭环稳态转速爬升跟踪
    _cov_hit_line(1, 114);
                if (_cov_hit_branch(7, (g_telemetry.speed_rpm < 2000.0f))) {
    _cov_hit_line(1, 115);
                    g_telemetry.speed_rpm += 20.0f;
                }
            }
    _cov_hit_line(1, 118);
            break;

        case MOTOR_STATE_DERATING:
    _cov_hit_line(1, 121);
            if (_cov_hit_branch(8, (!is_safe))) {
    _cov_hit_line(1, 122);
                g_telemetry.state = MOTOR_STATE_FAULT;
    _cov_hit_line(1, 123);
                bsp_pwm_disable_outputs();
    _cov_hit_line(1, 124);
            } else if (_cov_hit_branch(9, (g_telemetry.temperature_c <= 75.0f))) {
                // 温度恢复正常，切回全功率闭环
    _cov_hit_line(1, 126);
                g_telemetry.state = MOTOR_STATE_CLOSED_LOOP;
            }
    _cov_hit_line(1, 128);
            break;

        case MOTOR_STATE_FAULT:
            // 故障状态下确保 PWM 封锁
    _cov_hit_line(1, 132);
            bsp_pwm_disable_outputs();
    _cov_hit_line(1, 133);
            break;

        case MOTOR_STATE_EMERGENCY_STOP:
        default:
    _cov_hit_line(1, 137);
            bsp_pwm_disable_outputs();
    _cov_hit_line(1, 138);
            break;
    }
}

/**
 * @brief 10Hz 低频总线通讯与诊断广播任务 (100ms 周期执行)
 */
void Task_10Hz_Diagnostics(void)
{
    _cov_hit_line(1, 147);
    CanFrame_t tx_status_frame;
    _cov_hit_line(1, 148);
    CanFrame_t tx_telemetry_frame;

    // 1. 打包状态上报报文并广播
    _cov_hit_line(1, 151);
    if (_cov_hit_branch(10, (CAN_Comm_PackStatusFrame(&tx_status_frame, &g_telemetry)))) {
        // 模拟底层驱动发送
    }

    // 2. 打包电气参数遥测报文并广播
    _cov_hit_line(1, 156);
    if (_cov_hit_branch(11, (CAN_Comm_PackTelemetryFrame(&tx_telemetry_frame, &g_telemetry)))) {
        // 模拟底层驱动发送
    }
}

/**
 * @brief 系统硬件板级支持包与底层外设上电自检与初始化
 */
bool System_Hardware_Init(void)
{
    // 1. 初始化定时器与三相驱动桥
    _cov_hit_line(1, 167);
    if (_cov_hit_branch(12, (bsp_pwm_init())) != 0) {
    _cov_hit_line(1, 168);
        return false;
    }

    // 2. 初始化 ISO 26262 功能安全监控单元
    _cov_hit_line(1, 172);
    safety_monitor_init();

    // 3. 初始化车载 CAN 通信总线协议栈
    _cov_hit_line(1, 175);
    if (_cov_hit_branch(13, (!CAN_Comm_Init()))) {
    _cov_hit_line(1, 176);
        return false;
    }

    // 4. 执行相电流传感器上电静态校准
    _cov_hit_line(1, 180);
    if (_cov_hit_branch(14, (!bsp_pwm_calibrate_offsets()))) {
    _cov_hit_line(1, 181);
        safety_monitor_report_fault(FAULT_CALIBRATION_FAIL);
    _cov_hit_line(1, 182);
        return false;
    }

    _cov_hit_line(1, 185);
    return true;
}

/**
 * @brief 嵌入式固件主入口函数
 */
int main(void)
{
    // 1. 底层板级硬件与驱动协议初始化
    _cov_hit_line(1, 194);
    if (_cov_hit_branch(15, (!System_Hardware_Init()))) {
    _cov_hit_line(1, 195);
        g_telemetry.state = MOTOR_STATE_FAULT;
    } else {
    _cov_hit_line(1, 197);
        g_telemetry.state = MOTOR_STATE_STANDBY;
    }

    // 2. 确定性周期多速率主轮询调度循环 (模拟 RTOS 或裸机大循环)
    _cov_hit_line(1, 201);
    uint32_t counter_100hz = 0;
    _cov_hit_line(1, 202);
    uint32_t counter_10hz = 0;

    while (g_system_running && g_system_tick_ms < 5000) {
        // 模拟 1ms 硬件定时器系统滴答
    _cov_hit_line(1, 206);
        g_system_tick_ms++;
    _cov_hit_line(1, 207);
        counter_100hz++;
    _cov_hit_line(1, 208);
        counter_10hz++;

        // 模拟 10kHz 中断 (每毫秒调用 10 次)
        for (int i = 0; i < 10; ++i) {
    _cov_hit_line(1, 212);
            ISR_10kHz_CurrentLoop();
        }

        // 10ms 周期任务 (100Hz)
    _cov_hit_line(1, 216);
        if (_cov_hit_branch(16, (counter_100hz >= 10))) {
    _cov_hit_line(1, 217);
            counter_100hz = 0;
    _cov_hit_line(1, 218);
            Task_100Hz_StateMachine();
        }

        // 100ms 周期任务 (10Hz)
    _cov_hit_line(1, 222);
        if (_cov_hit_branch(17, (counter_10hz >= 100))) {
    _cov_hit_line(1, 223);
            counter_10hz = 0;
    _cov_hit_line(1, 224);
            Task_10Hz_Diagnostics();
        }
    }

    // 安全关断退出
    _cov_hit_line(1, 229);
    bsp_pwm_disable_outputs();
    _cov_hit_line(1, 230);
    return 0;
}

